/* scripts/lib/prehled.js — statická textová podoba celého hodnocení.
 *
 * Web je jednostránková aplikace: v surovém HTML je jen <div id="root"></div>
 * a obsah dotahuje JavaScript. Google ho spustí, roboti krmící AI vyhledávání
 * většinou ne — pro ty je celý web prázdný. Tahle stránka je táž data
 * v obyčejném HTML.
 *
 * NENÍ to stránka pro roboty. Je odkazovaná z webu a kdokoli ji může otevřít;
 * servírovat robotům něco jiného než lidem je cloaking a Google za to vyhazuje
 * z indexu. Robot tu vidí přesně to, co člověk — jen bez interaktivity.
 *
 * Vedlejší efekty, kvůli kterým to stojí za to i bez vyhledávačů: funguje bez
 * JavaScriptu, dá se vytisknout, čtečky pro nevidomé si s ní poradí a načte se
 * i na špatném připojení.
 *
 * Generuje se při buildu (viz vite.config.js) do /prehled/ a /overview/.
 */

const ORIGIN = "https://vladomer.cz";

const T = {
  cs: {
    lang: "cs", cesta: "prehled", druha: "overview",
    titulek: "Přehled plnění programového prohlášení vlády — Vládoměr",
    h1: "Plnění programového prohlášení vlády Andreje Babiše",
    popis: "Textový přehled hodnocení všech 143 závazků z programového prohlášení vlády. Aktualizuje se každý pátek.",
    uvod: "Toto je úplný textový výpis hodnocení. Obsahuje stejná data jako interaktivní verze, jen bez filtrování a grafů — funguje bez JavaScriptu a dá se vytisknout.",
    zpet: "Interaktivní verze na vladomer.cz",
    druhyJazyk: "English version",
    souhrn: "Souhrn",
    splneno: "splněno", castecne: "částečně splněno", probiha: "probíhá", poruseno: "porušeno",
    hodnocenoZ: (n, c) => `${n} z ${c} závazků hodnoceno`,
    vyhrada: "Hodnotí jazykový model podle veřejné metodiky. Orientační a neoficiální, ne oficiální statistika.",
    stavK: "Stav k",
    metodika: "Jak se hodnotí",
    metodikaText: "Hodnocení generuje jazykový model podle veřejné metodiky, na základě vyhledávání ve vybraných zdrojích. Je orientační a neoficiální, může obsahovat chyby a nenahrazuje ověření v primárních zdrojích. Stav „splněno“ vyžaduje, aby změna prošla celým legislativním procesem a byla vyhlášena ve Sbírce zákonů; body, které nejde měřit, jsou z procent vyloučeny.",
    aktualizovano: "Naposledy aktualizováno",
    neproběhlo: "Hodnocení zatím neproběhlo.",
    doklad: "Doklad",
    zdroje: "Zdroje",
    nehodnoceno: "Nehodnoceno",
    nemeritelne: "neměřitelné",
    /* Bez tohohle by ve výpisu stál odznak „částečně splněno“ nad komentářem,
       který tvrdí opak — a tenhle výpis čtou hlavně roboti, kteří si to
       nerozklíčují. Stejné texty jsou v aplikaci. */
    snizeno: "Sníženo kontrolou",
    snizenoProc: {
      "no-evidence": "model uvedl „splněno“, ale nedoložil to ničím konkrétním.",
      "no-date": "model uvedl „splněno“, ale doklad nemá datum.",
      "predates-term": "doložený krok proběhl před nástupem této vlády.",
      "date-mismatch": "jediné, co doklad váže k této vládě, je den, kdy starší předpis začal platit.",
      "not-through-process": "doklad popisuje návrh, který teprve míří do Sněmovny, ne normu, která prošla celým procesem.",
      "broken-no-evidence": "pro tvrzení o porušení slibu nebyl uveden žádný konkrétní doklad.",
    },
    zdrojProgramu: "Zdroj: programové prohlášení vlády",
    dataText: "Data ke stažení",
    licence: "Data a hodnocení jsou k volnému použití s uvedením zdroje pod licencí",
    citace: (d) => `Doporučené uvedení: „Zdroj: Vládoměr (vladomer.cz), CC BY 4.0${d ? `, stav k ${d}` : ""}.“`,
    stavy: {
      fulfilled: "Splněno", partial: "Částečně splněno", in_progress: "Probíhá",
      declared: "Jen deklarováno", not_started: "Nezahájeno", broken: "Porušeno / opuštěno",
      stalled: "Porušeno / opuštěno",
    },
  },
  en: {
    lang: "en", cesta: "overview", druha: "prehled",
    titulek: "Government programme delivery — full listing — Vládoměr",
    h1: "Delivery of the Babiš government's programme statement",
    popis: "Plain-text listing of the assessment of all 143 commitments in the Czech government's programme statement. Updated every Friday.",
    uvod: "This is the complete listing of the assessment. It holds the same data as the interactive version, without the filtering and charts — it works without JavaScript and can be printed.",
    zpet: "Interactive version at vladomer.cz",
    druhyJazyk: "Česká verze",
    souhrn: "Summary",
    splneno: "fulfilled", castecne: "partially fulfilled", probiha: "in progress", poruseno: "broken",
    hodnocenoZ: (n, c) => `${n} of ${c} commitments assessed`,
    vyhrada: "Rated by a language model following a public methodology. Indicative and unofficial, not an official statistic.",
    stavK: "As of",
    metodika: "How this is assessed",
    metodikaText: "Ratings are generated by a language model following a public methodology, from searches across a fixed list of sources. They are indicative and unofficial, may contain errors, and are no substitute for checking primary sources. “Fulfilled” requires the change to have cleared the entire legislative process and been published in the Collection of Laws; commitments too vague to measure are excluded from the percentages.",
    aktualizovano: "Last updated",
    neproběhlo: "No assessment has run yet.",
    doklad: "Evidence",
    zdroje: "Sources",
    nehodnoceno: "Unrated",
    nemeritelne: "unmeasurable",
    snizeno: "Downgraded by check",
    snizenoProc: {
      "no-evidence": "the model said “fulfilled” but cited nothing concrete.",
      "no-date": "the model said “fulfilled” but the evidence carries no date.",
      "predates-term": "the step cited happened before this cabinet took office.",
      "date-mismatch": "the only thing tying the evidence to this cabinet is the day an older rule took effect.",
      "not-through-process": "the evidence describes a bill still on its way to parliament, not a law that completed the process.",
      "broken-no-evidence": "no concrete evidence was given for the claim that the promise was broken.",
    },
    zdrojProgramu: "Source: the government's programme statement",
    dataText: "Download the data",
    licence: "The data and assessments are free to reuse with attribution, under",
    citace: (d) => `Suggested attribution: “Source: Vládoměr (vladomer.cz), CC BY 4.0${d ? `, as of ${d}` : ""}.”`,
    stavy: {
      fulfilled: "Fulfilled", partial: "Partially fulfilled", in_progress: "In progress",
      declared: "Declared only", not_started: "Not started", broken: "Broken / abandoned",
      stalled: "Broken / abandoned",
    },
  },
};

const BARVY = {
  fulfilled: "#15803D", partial: "#B45309", in_progress: "#0369A1",
  declared: "#6B7280", not_started: "#6B7280", broken: "#BE123C", stalled: "#BE123C",
};

/* "stalled" je stará hodnota škály z doby před 7/2026. Musí tu být, aby se
   jmenovatel shodoval s App.jsx (score: 1) — a taky proto, že metriky() ji
   níž počítá do „porušeno“, což by bez ní byl kód, který nikdy nenastane. */
const SCORED = new Set(["fulfilled", "partial", "in_progress", "declared", "not_started", "broken", "stalled"]);

function esc(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function datum(iso, lang) {
  if (!iso) return null;
  return new Date(iso).toLocaleDateString(lang === "cs" ? "cs-CZ" : "en-GB",
    { day: "numeric", month: "long", year: "numeric" });
}

/* Stejná přísná metrika jako src/App.jsx i scripts/og-image.js. Kdyby se
   rozešly, tvrdí každá stránka jiné číslo o téže vládě. */
function metriky(items, evals) {
  let done = 0, partial = 0, prog = 0, broken = 0, n = 0, unver = 0;
  for (const it of items) {
    const v = evals[it.id];
    if (!v || !SCORED.has(v.status)) continue;
    if (v.unverifiable) { unver++; continue; }
    n++;
    if (v.status === "fulfilled") done++;
    else if (v.status === "partial") partial++;
    else if (v.status === "in_progress") prog++;
    else if (v.status === "broken" || v.status === "stalled") broken++;
  }
  const p = (x) => (n ? (x / n) * 100 : 0);
  const one = (v) => (v >= 10 || v === 0 ? Math.round(v) : Math.round(v * 10) / 10);
  return { done: one(p(done)), partial: one(p(partial)), prog: one(p(prog)), broken: one(p(broken)), n, unver };
}

const CSS = `
:root{color-scheme:light dark;--bg:#fff;--fg:#16202E;--muted:#5A6b80;--line:#E2E8F0;--card:#F8FAFC;--link:#1D4ED8}
@media(prefers-color-scheme:dark){:root{--bg:#0B0F19;--fg:#E8ECF4;--muted:#94A3B8;--line:#1E293B;--card:#121824;--link:#7DA2FF}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.6 system-ui,-apple-system,"Segoe UI","DejaVu Sans",sans-serif}
.wrap{max-width:820px;margin:0 auto;padding:32px 20px 64px}
h1{font-size:29px;line-height:1.25;margin:0 0 10px}
h2{font-size:22px;margin:44px 0 4px;padding-top:22px;border-top:1px solid var(--line)}
h3{font-size:15px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);margin:26px 0 10px;font-weight:700}
p{margin:0 0 12px}
a{color:var(--link)}
.lede{color:var(--muted)}
.nav{display:flex;flex-wrap:wrap;gap:8px 18px;margin:0 0 26px;font-size:14.5px}
.sum{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px 20px;margin:0 0 8px}
.sum dl{display:flex;flex-wrap:wrap;gap:8px 32px;margin:0}
.sum div{margin:0}
.sum dt{font-size:13.5px;color:var(--muted)}
.sum dd{margin:0;font-size:26px;font-weight:750;font-variant-numeric:tabular-nums}
/* Výhrada sedí uvnitř rámečku s čísly schválně. Kdo číslo vytrhne — člověk
   i jazykový model — vytrhne s ním i to, jak vzniklo a k jakému je dni.
   O odstavec níž se oddělit dá, odsud podstatně hůř. */
.sum .caveat{margin:14px 0 0;padding-top:12px;border-top:1px solid var(--line);
  font-size:13.5px;line-height:1.5;color:var(--muted)}
.note{font-size:14px;color:var(--muted);margin:0 0 26px}
ol.items{list-style:none;margin:0;padding:0}
li.item{border-bottom:1px solid var(--line);padding:16px 0}
li.item:last-child{border-bottom:0}
.hd{display:flex;flex-wrap:wrap;align-items:baseline;gap:8px 10px}
.title{font-weight:650;flex:1 1 300px}
.id{font:12.5px/1 ui-monospace,"DejaVu Sans Mono",monospace;color:var(--muted)}
.badge{display:inline-block;font-size:12.5px;font-weight:700;color:#fff;padding:3px 9px;border-radius:999px;white-space:nowrap}
.cmt{margin:8px 0 0;color:var(--fg)}
.ev{margin:8px 0 0;font-size:14.5px;color:var(--muted)}
.dg{margin:8px 0 0;font-size:14.5px;padding:6px 10px;border-left:3px solid #B45309;background:rgba(180,83,9,.07)}
.src{margin:8px 0 0;padding:0;list-style:none;font-size:14px}
.src li{margin:3px 0}
footer{margin-top:52px;padding-top:20px;border-top:1px solid var(--line);font-size:14px;color:var(--muted)}
@media print{body{background:#fff;color:#000}.nav{display:none}a{color:#000;text-decoration:none}}
`;

export function renderPrehled(lang, { chapters, evals, lastUpdated, totalItems }) {
  const t = T[lang];
  const items = chapters.flatMap((c) => c.groups.flatMap((g) => g.items));
  const m = metriky(items, evals);
  const kdy = datum(lastUpdated, lang);

  /* Česky desetinná čárka a úzká mezera před procentem, anglicky tečka a bez
     mezery. Bez tohohle stálo na anglické stránce „3,5 %“. */
  const procento = (v) => (lang === "cs"
    ? `${String(v).replace(".", ",")}&#8239;%`
    : `${v}%`);

  const cisla = [
    [t.splneno, m.done, BARVY.fulfilled],
    [t.castecne, m.partial, BARVY.partial],
    [t.probiha, m.prog, BARVY.in_progress],
    [t.poruseno, m.broken, BARVY.broken],
  ].map(([k, v, c]) =>
    `<div><dt>${esc(k)}</dt><dd style="color:${c}">${procento(v)}</dd></div>`
  ).join("");

  const telo = chapters.map((ch) => {
    const skupiny = ch.groups.map((g) => {
      const body = g.items.map((it) => {
        const e = evals[it.id];
        const stav = e && t.stavy[e.status] ? t.stavy[e.status] : t.nehodnoceno;
        const barva = (e && BARVY[e.status]) || "#6B7280";
        const komentar = e && e.comment && e.comment[lang] ? e.comment[lang] : "";
        const doklad = e && e.evidence ? e.evidence : "";
        const snizeno = e && t.snizenoProc[e.evidenceMissing] ? e.evidenceMissing : "";
        const zdroje = (e && Array.isArray(e.sources) ? e.sources : [])
          .filter((s) => s && s.url)
          .map((s) => `<li><a href="${esc(s.url)}">${esc(s.title || s.url)}</a></li>`)
          .join("");
        return `<li class="item">
<div class="hd"><span class="title">${esc(it[lang])}</span>`
          + `<span class="badge" style="background:${barva}">${esc(stav)}</span>`
          + `<span class="id">#${esc(it.id)}</span></div>`
          + (e && e.unverifiable ? `<p class="ev">(${esc(t.nemeritelne)})</p>` : "")
          // Před komentářem, ne za ním: rámuje ho, aby čtenář nenarazil nejdřív
          // na tvrzení modelu o splnění a až potom zjistil, že neobstálo.
          + (snizeno ? `<p class="dg"><strong>${esc(t.snizeno)}:</strong> ${esc(t.snizenoProc[snizeno])}</p>` : "")
          + (komentar ? `<p class="cmt">${esc(komentar)}</p>` : "")
          + (doklad ? `<p class="ev"><strong>${esc(t.doklad)}:</strong> ${esc(doklad)}</p>` : "")
          + (zdroje ? `<ul class="src">${zdroje}</ul>` : "")
          + `</li>`;
      }).join("\n");
      const nadpis = g.title && g.title[lang] ? `<h3>${esc(g.title[lang])}</h3>` : "";
      return `${nadpis}<ol class="items">${body}</ol>`;
    }).join("\n");
    return `<section><h2>${esc(ch.id)}. ${esc(ch.title[lang])}</h2>\n${skupiny}</section>`;
  }).join("\n");

  return `<!doctype html>
<html lang="${t.lang}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(t.titulek)}</title>
<meta name="description" content="${esc(t.popis)}" />
<link rel="canonical" href="${ORIGIN}/${t.cesta}/" />
<link rel="alternate" hreflang="cs" href="${ORIGIN}/prehled/" />
<link rel="alternate" hreflang="en" href="${ORIGIN}/overview/" />
<link rel="alternate" hreflang="x-default" href="${ORIGIN}/prehled/" />
<link rel="icon" href="../favicon.svg" type="image/svg+xml" />
<style>${CSS}</style>
</head>
<body>
<div class="wrap">
<main>
<h1>${esc(t.h1)}</h1>
<p class="lede">${esc(t.uvod)}</p>
<nav class="nav">
  <a href="../">${esc(t.zpet)}</a>
  <a href="../${t.druha}/" hreflang="${lang === "cs" ? "en" : "cs"}">${esc(t.druhyJazyk)}</a>
  <a href="../evaluations.json">${esc(t.dataText)}</a>
</nav>

<h2 style="border-top:0;padding-top:0;margin-top:0">${esc(t.souhrn)}</h2>
<div class="sum">
<dl>${cisla}</dl>
<p class="caveat">${esc(t.vyhrada)} `
    + (kdy ? `${esc(t.stavK)} <time datetime="${esc(String(lastUpdated).slice(0, 10))}">${esc(kdy)}</time>. ` : `${esc(t.neproběhlo)} `)
    + `${esc(t.hodnocenoZ(m.n, totalItems))}${m.unver ? `, ${m.unver} ${esc(t.nemeritelne)}` : ""}.</p>
</div>
<p class="note">${esc(t.metodikaText)}</p>

${telo}
</main>
<footer>
<p>${esc(t.zdrojProgramu)} · <a href="https://vlada.gov.cz/cz/vlada/programove-prohlaseni/programove-prohlaseni-vlady-224629/">vlada.gov.cz</a></p>
<p>${esc(t.licence)} <a href="https://creativecommons.org/licenses/by/4.0/deed.cs" rel="license">CC BY 4.0</a>.
${esc(t.citace(kdy))}</p>
<p><a href="../">vladomer.cz</a></p>
</footer>
</div>
</body>
</html>
`;
}

export const CESTY = { cs: "prehled", en: "overview" };
